# code: language=ansible
# vim: set filetype=yaml.ansible :
---
- name: "validate vmalert configs"
  ansible.builtin.shell:
    cmd: |
      docker exec -i {{ victoriametrics_docker_compose_vmalert_container_name }} /vmalert-prod {% for cmd in victoriametrics_docker_compose_vmalert_commands %} {{ cmd }} {% endfor %} --dryRun
  register: vmalert_validate_result
  changed_when: false
  args:
    executable: /bin/bash

- name: "get vmalert container status"
  ansible.builtin.shell:
    cmd: "set -o pipefail && docker ps | grep '{{ victoriametrics_docker_compose_vmalert_container_name }}'"
  register: vmalert_container_result
  changed_when: false
  args:
    executable: /bin/bash

- name: "reload vmalert"
  ansible.builtin.uri:
    url: http://127.0.0.1:8880/-/reload
    dest: /tmp/vmalert-reload
    mode: '0644'
    method: POST
  when:
    - "'finished reading ' in vmalert_validate_result.stderr"
    - "'Up ' in vmalert_container_result.stdout"

- name: "up vmalert"
  community.docker.docker_compose_v2:
    services:
      - "{{ victoriametrics_docker_compose_vmalert_container_name }}"
    state: present
    project_src: "{{ victoriametrics_docker_compose_root_folder }}"
  when:
    - "'finished reading ' in vmalert_validate_result.stderr"
    - "'Up ' not in vmalert_container_result.stdout"

- name: "restart vmalert-vl"
  community.docker.docker_compose_v2:
    services:
      - "{{ victoriametrics_docker_compose_vmalert_container_name }}"
    state: restarted
    project_src: "{{ victoriametrics_docker_compose_root_folder }}"
  when:
    - "'finished reading ' in vmalert_validate_result.stdout"
    - "'Up ' not in vmalert_container_result.stdout"
