# code: language=ansible
# vim: set filetype=yaml.ansible :
---
- name: Converge
  hosts: all
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: install docker
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
          - docker-cli

    - name: start docker
      ansible.builtin.systemd:
        name: docker
        state: started

    - name: "include victoriametrics_docker role"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'GITHUB_WORKSPACE') }}"
